### ISSUE TITLE
Hello, IDML files to Xliff issue

### ISSUE THREAD

**Issue by ImKijung** [rmraya/OpenXLIFF#10]
When the IDML file convert to Xliff file, the order of open tag and close tag (of the element "Content" and "CharacterStyleRange") are reversed.
Can you fix it?

**Comment by rmraya** [comment]
Can you provide an example?

**Comment by ImKijung** [comment]
[DB68-06095A-04_IBIM_NASA DMS2.5 BACnet LW_EU_EN_.idml.zip](https://github.com/rmraya/OpenXLIFF/files/6255811/DB68-06095A-04_IBIM_NASA.DMS2.5.BACnet.LW_EU_EN_.idml.zip)

Here you are. Thanks.

**Comment by rmraya** [comment]
I don't se where the problem is. Conversion to XLIFF and back work as expected.
