### ISSUE TITLE
Does OpenXLIFF support TMX file?

### ISSUE THREAD

**Issue by handhikadj** [rmraya/OpenXLIFF#12]
I got `java.io.IOException: Configuration file 'config_tmx.xml' not found.` when converting from TMX to XLIFF using this

**Comment by rmraya** [comment]
OpenXLIFF supports almost any XML format. You need to write the appropriate configuration file.

**Comment by handhikadj** [comment]
How do I write it? I don't have any reference how to write the `config_tmx.xml`
