### ISSUE TITLE
Make ILogger deterministic for some stages of processing

### ISSUE THREAD

**Issue by AlexJitianu** [rmraya/OpenXLIFF#17]
Hello,

We are currently building an Oxygen XML Editor plugin that integrates Fluenta into the DITA Maps Manager. We are using {{com.maxprograms.fluenta.API}} for calling Fluenta operations. I've noticed that there is a {{com.maxprograms.tmengine.ILogger}} interface for notifying progress. The progress is indeterminate, but for some stages it looks like it could become deterministic. For example, in {{DitaMap2Xliff}} after setting the stage to _Processing Files_ you know how many files will be processed.

**Comment by rmraya** [comment]
DitaMap2Xlifffilter already uses com.maxprograms.converters.ILogger interface.

The interface com.maxprograms.tmengine.ILogger is outdated and may be removed from Fluenta

**Comment by AlexJitianu** [comment]
My observation applies to `com.maxprograms.converters.ILogger` as well, which is also nondeterministic. It would help users get an idea understand how much they have to wait until the process is over.
