### ISSUE TITLE
Improvement | config_dita | image 

### ISSUE THREAD

**Issue by lmiu** [rmraya/OpenXLIFF#18]
Current config for image
<tag hard-break="inline" ctype="image" attributes="alt;longdescref">image</tag>

According to 
https://docs.oasis-open.org/dita/dita/v1.3/csprd01/part3-all-inclusive/non-normative/elementsMerged.html
<image placement="break"> should break segment whereas <image> with other attribute or no attribute shall be inline.

**Request**
Add config support to cover \<image placement="break"\> case.

**Comment by rmraya** [comment]
The filter does not check whether the "placement" attribute in <image> is set to "placement" or "break".
