### ISSUE TITLE
config_dita | Missing config

### ISSUE THREAD

**Issue by lmiu** [rmraya/OpenXLIFF#20]
According to this example
`<learningOverview id="overview">
  <title>Learning Overview topic</title>
  <learningOverviewbody>
    <lcObjectives>
    <title>Objectives</title>
    <lcObjectiveStem>When you complete this lesson, you'll know how to do the
     following:</lcObjectiveStem>
      <lcObjectivesGroup>
        <lcObjective>Create a good learning overview topic.</lcObjective>
        <lcObjective>Identify clear learning objectives.</lcObjective>
        <lcObjective>Add good test items to assess knowledge gained.</lcObjective>
      </lcObjectivesGroup>
    </lcObjectives>
  </learningOverviewbody>
</learningOverview>`

The following config is missing
<tag hard-break="segment" attributes="spectitle">lcObjective</tag>

**Comment by rmraya** [comment]
This is handled by <li>
