### ISSUE TITLE
Getting null pointer exception error with v3.7

### ISSUE THREAD

**Issue by davidarndtsick** [rmraya/OpenXLIFF#25]
Hi, I'm getting a null pointer Exception with version 3.7 on Windows 10 when executing any of the bat commands.
v3.4 works fine.

![image](https://github.com/rmraya/OpenXLIFF/assets/127110657/49c80205-11cb-4a82-9a50-b5908c152c65)

Best regards,
David

**Comment by rmraya** [comment]
Cannot reproduce.

**Comment by rmraya** [comment]
Get version 3.8.0. It may solve the issue you have if your computer is not running in English

**Comment by davidarndtsick** [comment]
Thanks! Yes that fixed the issue. My Windows version is running in German :)
