### ISSUE TITLE
How I ignore validate Schema when load DITA file?

### ISSUE THREAD

**Issue by devomniscien** [rmraya/OpenXLIFF#26]
Hello, 

     I ran converting the DITA file to XLIFF file. But I do not have dtd file. How I run your program without dtd file? 
     
     error:
![image](https://github.com/rmraya/OpenXLIFF/assets/144361614/6d4601bd-c85a-4853-abe4-939e430f575b)

Best Regards,
Dev Omniscien
[Ex-Test-DTD.zip](https://github.com/rmraya/OpenXLIFF/files/12550539/Ex-Test-DTD.zip)

**Comment by rmraya** [comment]
Your file declares a grammar:

`<!DOCTYPE concept PUBLIC "-//IXIA//DTD IXIA DITA Composite//EN" "IxiaDitabase.dtd">`

The declared DTD is essential to process elements using the default value of the `class `attribute.

If you don't add the DTD to the catalog, processing will fail.

Ask Ixiasoft to provide the catalog and include it in your file set. If you get the catalog and permission to share it, I can include it in OpenXLIFF's default catalog.
