### ISSUE TITLE
Setting to treat SVGs as binary

### ISSUE THREAD

**Issue by raducoravu** [rmraya/OpenXLIFF#31]
For the Oxygen Fluenta add-on we have a client using it and the client would like the generated xliff to treat SVGs as binary images as the client is not interested in translating the SVGs. Looking at the code there does not seem to be a setting to state that SVGs should be treated as binary.

**Comment by rmraya** [comment]
Your observation is correct. There is no option to treat linked SVG files as binaries.

**Comment by raducoravu** [comment]
Thanks @rmraya, could this be interpreted as a feature request? Maybe other users would benefit from being able to choose this behavior.

**Comment by rmraya** [comment]
I have no plans to implement this change. If anyone is interested in sponsoring the development, I would consider it.

**Comment by raducoravu** [comment]
+1 another end user complaining that for a DITA project with topics summing about 200kbytes on disk they get an xliff of about 100MBs as the xliff contains the expanded svg images.

**Comment by raducoravu** [comment]
I see this was implemented in the Fluenta 5.0 release:

Added option to ignore translatable SVG files
