### ISSUE TITLE
Renaming xliff files results in merged files without suffix

### ISSUE THREAD

**Issue by MartinAlacam** [rmraya/OpenXLIFF#33]
> martin@smrad ~/test> ls 
> test_en.docx  test_en.docx.skl  test_en.docx.xlf
> martin@smrad ~/test> mv test_en.docx.xlf test_BAK.xlf
> martin@smrad ~/test> ~/Applications/OpenXLIFF/merge.sh -xliff test_BAK.xlf 
> martin@smrad ~/test> ls
>test_BAK  test_BAK.xlf  test_en.docx  test_en.docx.skl

test_BAK doesn't have the source file's suffix.

But I also think the merged file's name should always follow the source file name and not the XLIFF, i.e, test_en.docx should become test_en_tr.docx no matter what the xlf is named.

**Comment by rmraya** [comment]
Use `-target` option.

**Comment by MartinAlacam** [comment]
`-target` option is not mentioned in the -h help. What does it do? It doesn't change the xlf name, neither is the option written anywhere into the xliff file.

**Comment by MartinAlacam** [comment]
OK got it. Still, I think the suffix should be correct in all cases.
