### ISSUE TITLE
Error merging SDLXLIFF file containing sdl:locktype="Manual"

### ISSUE THREAD

**Issue by Abhishek9934** [rmraya/OpenXLIFF#36]
Openxliff is unable to merge sdlxliff file, the xlf file contains units like this. 

Error message - " The prefix "sdl" for attribute "sdl:locktype" associated with an element type "trans-unit" is not bound."

`
<unit sdl:locktype="Manual" translate="no" id="lockTU_f5e3ea65-08f7-4717-99e0-d38c632128af">
      <segment id="lockTU_f5e3ea65-08f7-4717-99e0-d38c632128af">
        <source xml:space="default">
          <pc id="g82">1</pc>
        </source>
      </segment>
    </unit>
`

Sharing the xlf and skl files that are not merging -

https://drive.google.com/file/d/15Dvl4uq_nr3CIOcC3hZXnPjL7IENNCSl/view?usp=sharing
https://drive.google.com/file/d/1dew6bfGRasSOMgUYBv7sUNbKyUMNg_mN/view?usp=sharing

**Comment by rmraya** [comment]
Please share the original SDLXLIFF file you tried to translate. There is something strange in your files, as OpenXLIFF should not add `sdl:locktype` attributes to the XLIFF files it creates.

**Comment by rmraya** [comment]
The file you shared as skeleton does not have the named specified in the XLIFF file.

**Comment by rmraya** [comment]
Cannot reproduce without the right files. Will reopen this issue if you provide the original SDLXLIFF and the translated XLIFF.

**Comment by Abhishek9934** [comment]
Hi, sharing the original file - https://drive.google.com/file/d/1tGFhmig3va8zRfzxeGfnVC8Elwz_47T4/view?usp=sharing

**Comment by rmraya** [comment]
Thanks for sending the file. I will investigate and release a fix.
