### ISSUE TITLE
Feature suggestion: Change spelling language of target document to the target language

### ISSUE THREAD

**Issue by foolo** [rmraya/OpenXLIFF#4]
I noticed that the output document keeps the spelling language of the source document.
Not sure whether this is an easy change or not, but it would be a nice improvement if the output document had the same spelling language as the target language.
Example of current behavior:
- ./convert.sh  -file msdoc.docx -srcLang en -tgtLang sv -2.0 -embed
- translate the text to Swedish
- ./merge.sh -xliff msdoc.docx.xlf -target msdoc_sv.docx
- open the output document msdoc_sv.docx,
- spelling language is English

**Comment by rmraya** [comment]
Will implement when creating XLIFF 2.0 by default.
