### ISSUE TITLE
For Indian Languages: Source text gets stored in a weird fashion in XLIFF format

### ISSUE THREAD

**Issue by vinayaksharmagh** [rmraya/OpenXLIFF#7]
For Indian languages like Hindi, Sanskrit etc., apart from the original text, "source" field contains metadata after each word. This is unusual and doesn't happen in case of western languages like English, French German etc.  This is problematic because CAT tools present the source field as is in the source language columns.

![Screenshot (211)](https://user-images.githubusercontent.com/41826895/97796398-80865b80-1c37-11eb-95f3-939a76532656.png)

I am attaching the original text file and the converted XLIFF files as well 
[OpenXLIFF.zip](https://github.com/rmraya/OpenXLIFF/files/5470287/OpenXLIFF.zip)

Update:
This is happening with OFF files but not in case of TEXT files.

**Comment by rmraya** [comment]
Hi,

The problem you face is quite common with Word documents created from scanned PDF, it is not something specific to Hindi or Sanskrit. Word tends to introduce too many font changes in the text to optimize text appearance. Documents look good for printing, but they are bad for translating.

You need to prepare your Word documents before converting them to XLIFF. There are several tools that can clear the excess of tags that your document has (search "CodeZapper tags").

Thank you for the sample files. I'll try to improve the code using them. Don't expect miracles, though.

Rodolfo M. Raya

**Comment by vinayaksharmagh** [comment]
Thanks for the explanation! I will try the technique that you have mentioned.

**Comment by rmraya** [comment]
Current code produces cleaner XLIFF from your Hindi file. For the Sanskrit sample, there are still many tags, but simpler ones. If you set all text to the same font output is clean.
