### ISSUE TITLE
IDML to XLIFF identify page

### ISSUE THREAD

**Issue by oussama-touzni** [rmraya/OpenXLIFF#9]
First of all thanks for this great toolsuite 👍 
I've converted an IDML file -> XLIFF and I want to know is there any way to identity the pages to which the translation units belong ?

**Comment by rmraya** [comment]
Hi,

The IDML filter does not track page number, it tracks the story name, creating one <file> element per story. Story data is place in the header of each file.

Regards,
Rodolfo M. Raya
